### ISSUE TITLE
Document multichoice elections

### ISSUE THREAD

**Issue by selankon** [vocdoni/developer-portal#136]
This are different from the approval ones, and are typed and supported on the sdk and the ui components, but not documented anywhere on the developer portal:

https://developer.vocdoni.io/sdk/integration-details/voting-types

**Comment by selankon** [comment]
After talk with  @elboletaire we agreed on how the voting package have to be interpreted: 

![image](https://github.com/user-attachments/assets/f5327726-e5f3-43ef-a8a7-82f7e45fada3)

For this image the resulting voting package is: 

`[3, 2, 0, 4]`: option 3 selected, option 2 selectied, option 0 selected and option 4 selected.

On this case, option 4th is an abstain. Is not shown here but the election accepts abstention that are options added on the election that are not represented on the Ui design

**Comment by elboletaire** [comment]
It's quite obvious the vote envelope is not always showing the options properly sorted, kindly reminder to sort them :)

**Comment by selankon** [comment]
When documenting this, take  a look to this comment also https://github.com/vocdoni/explorer/issues/91#issuecomment-2272944148 to check if is interesting to add this info somehwere on the dev portal. 

Provably won't be needed (the vote packages are well documented on each election type)

**Comment by elboletaire** [comment]
Superseeded by #140
